services:
  - type: web
    name: ai-assisted-collaborative-code-platform
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT --threads 25 app:app
    disk:
      name: app-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATA_DIR
        value: /var/data
